// frontend-angular/src/app/components/bioreactor-model/bioreactor-model.component.ts
import { Component, Input, OnChanges, OnDestroy, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SimState, FaultEntry } from '../../models/simulation.model';

const IMG_W = 1376, IMG_H = 768, IMG_ASPECT = IMG_W / IMG_H;

// anchor: 'center' → badge centered on x (default)
//         'left'   → badge's LEFT  edge starts at x (safe near left  image edge)
//         'right'  → badge's RIGHT edge ends   at x (safe near right image edge)
const ANNOTATIONS = [
  { key: 'press', label: 'Pressure', xF: 0.99, yF: 0.06, fmt: (v: number) => v.toFixed(3), unit: ' bar',            anchor: 'right' },
  { key: 'pH',    label: 'pH',       xF: 0.99, yF: 0.27, fmt: (v: number) => v.toFixed(2), unit: '',                anchor: 'right' },
  { key: 'do',    label: 'DO',       xF: 0.99, yF: 0.50, fmt: (v: number) => v.toFixed(1), unit: ' %',              anchor: 'right' },
  { key: 'temp',  label: 'Temp',     xF: 0.99, yF: 0.73, fmt: (v: number) => v.toFixed(1), unit: ' °C',             anchor: 'right' },
  { key: 'vcd',   label: 'VCD',      xF: 0.01, yF: 0.15, fmt: (v: number) => (v / 1e6).toFixed(2), unit: ' ×10⁶/mL', anchor: 'left' },
];

const LIMITS: Record<string, { aL: number; aH: number; lL: number; lH: number }> = {
  pH:    { aL: 6.9, aH: 7.5, lL: 6.5,  lH: 7.8 },
  do:    { aL: 20,  aH: 90,  lL: 10,   lH: 100 },
  temp:  { aL: 36,  aH: 38.5,lL: 34,   lH: 40 },
  press: { aL: 1.0, aH: 1.5, lL: 0.8,  lH: 2.0 },
};

const FAULT_CPP: Record<string, string[]> = {
  agitator_power_loss:['do'], sparger_blockage:['do'], gas_supply_failure:['do'],
  foam_overflow:['do'], viscosity_surge:['do'], antifoam_injection:['do'],
  impeller_shear:['do','vcd'], coolant_leak:['do'], exhaust_filter_clog:['do','press'],
  seed_hypoxia:['do','vcd'], do_probe_bias:['do'], pid_fault:['temp'],
  antifoam_overdose:['do'], ph_high:['pH'], ph_low:['pH'], ph_oscillation:['pH'],
  do_low_sustained:['do'], do_high:['do'], do_hunting:['do'],
  temp_high:['temp'], temp_low:['temp'], temp_ramp:['temp'],
};

const CAT_COLOR: Record<string, string> = { process:'#ef4444', sensor:'#f97316', excursion:'#a855f7' };
const STATUS_STYLE = {
  normal: { bg:'#f0fdf4', border:'#22c55e', lc:'#16a34a', vc:'#15803d' },
  alert:  { bg:'#fffbeb', border:'#f59e0b', lc:'#b45309', vc:'#92400e' },
  limit:  { bg:'#fef2f2', border:'#ef4444', lc:'#b91c1c', vc:'#991b1b' },
};

function status(key: string, v: number): 'normal' | 'alert' | 'limit' {
  const b = LIMITS[key]; if (!b) return 'normal';
  if (v < b.lL || v > b.lH) return 'limit';
  if (v < b.aL || v > b.aH) return 'alert';
  return 'normal';
}

export interface Badge {
  key: string; label: string; left: number; top: number;
  transform: string;
  formatted: string; st: typeof STATUS_STYLE['normal'];
  hasFault: boolean; faultColor: string;
}

@Component({
  selector: 'app-bioreactor-model',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bioreactor-model.component.html',
})
export class BioreactorModelComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() state: SimState | null = null;
  @Input() activeFaults: FaultEntry[] = [];
  @ViewChild('container') containerRef!: ElementRef<HTMLDivElement>;

  imgRect = { left: 0, top: 0, w: 0, h: 0 };
  badges: Badge[] = [];
  faultTags: { label: string; color: string; left: number; top: number }[] = [];
  timeLabel = '';
  private ro?: ResizeObserver;

  ngAfterViewInit(): void {
    this.ro = new ResizeObserver(() => this.recalc());
    this.ro.observe(this.containerRef.nativeElement);
    this.recalc();
  }

  ngOnChanges(): void { this.rebuild(); }
  ngOnDestroy(): void { this.ro?.disconnect(); }

  private recalc(): void {
    const el = this.containerRef.nativeElement;
    const cw = el.clientWidth, ch = el.clientHeight;
    if (!cw || !ch) return;
    const cA = cw / ch;
    let w: number, h: number, left: number, top: number;
    if (cA > IMG_ASPECT) { h = ch; w = ch * IMG_ASPECT; left = (cw - w) / 2; top = 0; }
    else                  { w = cw; h = cw / IMG_ASPECT; left = 0; top = (ch - h) / 2; }
    this.imgRect = { left, top, w, h };
    this.rebuild();
  }

  private rebuild(): void {
    if (!this.state || !this.imgRect.w) { this.badges = []; this.faultTags = []; return; }
    const s = this.state;
    const vals: Record<string, number> = {
      pH: s.pH, do: s.dissolved_oxygen_pct, temp: s.temperature_C,
      press: s.pressure_bar, vcd: s.viable_cell_density,
    };
    const faultedCPP: Record<string, FaultEntry> = {};
    for (const f of this.activeFaults) {
      for (const k of (FAULT_CPP[f.id] ?? [])) { faultedCPP[k] = f; }
    }
    const { left, top, w, h } = this.imgRect;
    this.badges = ANNOTATIONS.map(a => {
      const v = vals[a.key] ?? 0;
      const st = STATUS_STYLE[status(a.key, v)];
      const fault = faultedCPP[a.key];
      const xShift = a.anchor === 'left' ? '0%' : a.anchor === 'right' ? '-100%' : '-50%';
      return {
        key: a.key, label: a.label,
        left: left + w * a.xF,
        top:  top  + h * a.yF,
        transform: `translate(${xShift}, -50%)`,
        formatted: `${a.fmt(v)}${a.unit}`,
        st, hasFault: !!fault,
        faultColor: fault ? (CAT_COLOR[fault.category] || '#ef4444') : '',
      };
    });
    this.faultTags = this.activeFaults.map((f, i) => ({
      label: f.name, color: CAT_COLOR[f.category] || '#ef4444',
      left: left + 8,
      top:  top + h - 26 - i * 24,
    }));
    this.timeLabel = `t = ${s.time_h.toFixed(2)} h`;
  }
}

<div class="wrapper" #container>
  <div class="placeholder" *ngIf="!state">
    <span style="font-size:52px;opacity:.3">⚗</span>
    <p>Waiting for data…</p>
  </div>

  <ng-container *ngIf="state">
    <img src="/bioreactormodel.png" alt="Bioreactor schematic" class="img" draggable="false" />

    <!-- CPP badges -->
    <div *ngFor="let b of badges" class="badge"
         [style.left.px]="b.left"
         [style.top.px]="b.top"
         [style.transform]="b.transform"
         [style.background]="b.hasFault ? b.faultColor + '12' : b.st.bg"
         [style.border-color]="b.hasFault ? b.faultColor : b.st.border"
         [style.box-shadow]="b.hasFault ? '0 0 0 2px ' + b.faultColor + '40, 0 2px 6px rgba(0,0,0,.12)' : '0 1px 4px rgba(0,0,0,.08)'"
         [style.text-align]="b.transform.startsWith('translate(0') ? 'left' : 'center'"
         [style.min-width.px]="68">
      <div class="blabel" [style.color]="b.hasFault ? b.faultColor : b.st.lc">
        <span *ngIf="b.hasFault" style="font-size:9px">⚠ </span>{{ b.label }}
      </div>
      <div class="bvalue" [style.color]="b.hasFault ? b.faultColor : b.st.vc">{{ b.formatted }}</div>
    </div>

    <!-- Active fault tags -->
    <div *ngFor="let t of faultTags" class="fault-tag"
         [style.left.px]="t.left" [style.top.px]="t.top"
         [style.color]="t.color" [style.border-color]="t.color"
         [style.border-left-color]="t.color">
      ⚠ {{ t.label }}
    </div>

    <!-- Time stamp -->
    <div class="time-tag">{{ timeLabel }}</div>
  </ng-container>
</div>

<style>
.wrapper { position:relative; width:100%; height:100%; background:#fff; overflow:hidden; }
.img { width:100%; height:100%; object-fit:contain; display:block; }
.placeholder { height:100%; display:flex; flex-direction:column; align-items:center; justify-content:center; color:#94a3b8; gap:8px; font-size:13px; }
.badge { position:absolute; border:1.5px solid; border-radius:7px; padding:3px 9px; pointer-events:none; }
.blabel { font-size:9px; font-weight:700; text-transform:uppercase; letter-spacing:.06em; line-height:1; margin-bottom:2px; }
.bvalue { font-size:12px; font-weight:700; font-family:monospace; line-height:1; }
.fault-tag { position:absolute; background:#fff; border:1px solid; border-left:3px solid; border-radius:4px; padding:2px 8px; font-size:10px; font-weight:600; white-space:nowrap; pointer-events:none; box-shadow:0 1px 3px rgba(0,0,0,.08); }
.time-tag { position:absolute; top:8px; right:8px; background:rgba(255,255,255,.9); border:1px solid #e2e8f0; border-radius:4px; padding:2px 8px; font-size:11px; font-family:monospace; color:#64748b; pointer-events:none; }
</style>

// frontend/src/components/BioreactorModel.jsx
import { useRef, useState, useEffect } from 'react'

const IMG_W = 1376
const IMG_H = 768
const IMG_ASPECT = IMG_W / IMG_H   // 1.792

// CPP annotation positions as fractions of the rendered image rect
// anchor: 'center' (default) centers the badge on (x,y).
//         'left'  pins the badge's LEFT  edge to x (safe near left  edge).
//         'right' pins the badge's RIGHT edge to x (safe near right edge).
const CPP_ANNOTATIONS = [
  // Right-side sensors — staggered inward so badges don't stack
  { key: 'press', label: 'Pressure', xFrac: 0.99, yFrac: 0.06, fmt: v => v.toFixed(3), unit: ' bar',            anchor: 'right' },
  { key: 'pH',    label: 'pH',       xFrac: 0.99, yFrac: 0.27, fmt: v => v.toFixed(2), unit: '',                anchor: 'right' },
  { key: 'do',    label: 'DO',       xFrac: 0.99, yFrac: 0.50, fmt: v => v.toFixed(1), unit: ' %',              anchor: 'right' },
  { key: 'temp',  label: 'Temp',     xFrac: 0.99, yFrac: 0.73, fmt: v => v.toFixed(1), unit: ' °C',             anchor: 'right' },
  // Left-side — VCD pinned to the left edge with a small inset
  { key: 'vcd',   label: 'VCD',      xFrac: 0.01, yFrac: 0.15, fmt: v => (v / 1e6).toFixed(2), unit: ' ×10⁶/mL', anchor: 'left' },
]

// Which CPP keys are affected by each fault id
const FAULT_CPP = {
  agitator_power_loss:  ['do'],
  sparger_blockage:     ['do'],
  gas_supply_failure:   ['do'],
  foam_overflow:        ['do'],
  viscosity_surge:      ['do'],
  antifoam_injection:   ['do'],
  impeller_shear:       ['do', 'vcd'],
  coolant_leak:         ['do'],
  exhaust_filter_clog:  ['do', 'press'],
  seed_hypoxia:         ['do', 'vcd'],
  do_probe_bias:        ['do'],
  pid_fault:            ['temp'],
  antifoam_overdose:    ['do'],
  ph_high:              ['pH'],
  ph_low:               ['pH'],
  ph_oscillation:       ['pH'],
  do_low_sustained:     ['do'],
  do_high:              ['do'],
  do_hunting:           ['do'],
  temp_high:            ['temp'],
  temp_low:             ['temp'],
  temp_ramp:            ['temp'],
}

const CAT_COLOR = { process: '#ef4444', sensor: '#f97316', excursion: '#a855f7' }

const LIMITS = {
  pH:    { alertLow: 6.9, alertHigh: 7.5, limitLow: 6.5, limitHigh: 7.8 },
  do:    { alertLow: 20,  alertHigh: 90,  limitLow: 10,  limitHigh: 100 },
  temp:  { alertLow: 36,  alertHigh: 38.5, limitLow: 34, limitHigh: 40 },
  press: { alertLow: 1.0, alertHigh: 1.5, limitLow: 0.8, limitHigh: 2.0 },
}

function cppStatus(key, val) {
  const b = LIMITS[key]
  if (!b || val == null) return 'normal'
  if (val < (b.limitLow ?? -Infinity) || val > (b.limitHigh ?? Infinity)) return 'limit'
  if (val < (b.alertLow ?? -Infinity) || val > (b.alertHigh ?? Infinity)) return 'alert'
  return 'normal'
}

const STATUS_STYLE = {
  normal: { bg: '#f0fdf4', border: '#22c55e', labelColor: '#16a34a', valColor: '#15803d' },
  alert:  { bg: '#fffbeb', border: '#f59e0b', labelColor: '#b45309', valColor: '#92400e' },
  limit:  { bg: '#fef2f2', border: '#ef4444', labelColor: '#b91c1c', valColor: '#991b1b' },
}

export default function BioreactorModel({ state, activeFaults }) {
  const containerRef = useRef(null)
  const [imgRect, setImgRect] = useState({ left: 0, top: 0, w: 0, h: 0 })

  useEffect(() => {
    const el = containerRef.current
    if (!el) return
    const recalc = () => {
      const cw = el.clientWidth
      const ch = el.clientHeight
      if (!cw || !ch) return
      const cAspect = cw / ch
      let w, h, left, top
      if (cAspect > IMG_ASPECT) {
        h = ch; w = ch * IMG_ASPECT; left = (cw - w) / 2; top = 0
      } else {
        w = cw; h = cw / IMG_ASPECT; left = 0; top = (ch - h) / 2
      }
      setImgRect({ left, top, w, h })
    }
    recalc()
    const obs = new ResizeObserver(recalc)
    obs.observe(el)
    return () => obs.disconnect()
  }, [])

  if (!state) {
    return (
      <div ref={containerRef} style={styles.wrapper}>
        <div style={styles.placeholder}>
          <span style={{ fontSize: 52, opacity: 0.3 }}>⚗</span>
          <p style={{ color: '#94a3b8', marginTop: 8, fontSize: 13 }}>Waiting for data…</p>
        </div>
      </div>
    )
  }

  const vals = {
    pH:    state.pH,
    do:    state.dissolved_oxygen_pct,
    temp:  state.temperature_C,
    press: state.pressure_bar,
    vcd:   state.viable_cell_density,
  }

  // Build set of CPP keys that have an active fault
  const faultedCPP = {}   // key → [{ name, category }]
  for (const f of (activeFaults || [])) {
    const affected = FAULT_CPP[f.id] || []
    for (const k of affected) {
      if (!faultedCPP[k]) faultedCPP[k] = []
      faultedCPP[k].push(f)
    }
  }

  return (
    <div ref={containerRef} style={styles.wrapper}>
      <img
        src="/bioreactormodel.png"
        alt="Bioreactor schematic"
        style={styles.image}
        draggable={false}
      />

      {/* CPP badges */}
      {imgRect.w > 0 && CPP_ANNOTATIONS.map(({ key, label, xFrac, yFrac, fmt, unit, anchor }) => {
        const val   = vals[key]
        const st    = cppStatus(key, val)
        const c     = STATUS_STYLE[st]
        const faults = faultedCPP[key] || []
        const hasFault = faults.length > 0
        const faultColor = hasFault ? (CAT_COLOR[faults[0].category] || '#ef4444') : null
        // anchor controls which edge of the badge aligns to the x position:
        //   'left'   → badge starts at x (safe near left edge of image)
        //   'right'  → badge ends   at x (safe near right edge of image)
        //   'center' → badge is centered on x (default)
        const xShift = anchor === 'left' ? '0%' : anchor === 'right' ? '-100%' : '-50%'

        return (
          <div
            key={key}
            style={{
              position: 'absolute',
              left: imgRect.left + imgRect.w * xFrac,
              top:  imgRect.top  + imgRect.h * yFrac,
              transform: `translate(${xShift}, -50%)`,
              background: hasFault ? `${faultColor}12` : c.bg,
              border: `1.5px solid ${hasFault ? faultColor : c.border}`,
              borderRadius: 7,
              padding: '3px 9px',
              minWidth: 68,
              textAlign: 'center',
              pointerEvents: 'none',
              boxShadow: hasFault
                ? `0 0 0 2px ${faultColor}40, 0 2px 6px rgba(0,0,0,0.12)`
                : '0 1px 4px rgba(0,0,0,0.08)',
            }}
          >
            {/* Label row with optional fault icon */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 3, marginBottom: 2 }}>
              {hasFault && (
                <span style={{ fontSize: 9, color: faultColor, lineHeight: 1 }}>⚠</span>
              )}
              <span style={{
                fontSize: 9, fontWeight: 700,
                color: hasFault ? faultColor : c.labelColor,
                textTransform: 'uppercase', letterSpacing: '0.06em', lineHeight: 1,
              }}>
                {label}
              </span>
            </div>
            {/* Value */}
            <div style={{
              fontSize: 12, fontWeight: 700,
              color: hasFault ? faultColor : c.valColor,
              fontFamily: 'monospace', lineHeight: 1,
            }}>
              {val != null ? `${fmt(val)}${unit}` : '—'}
            </div>
          </div>
        )
      })}

      {/* Active fault tags stacked at bottom of image */}
      {imgRect.w > 0 && (activeFaults || []).map((f, i) => {
        const color = CAT_COLOR[f.category] || '#ef4444'
        return (
          <div
            key={f.id}
            style={{
              position: 'absolute',
              left: imgRect.left + 8,
              top:  imgRect.top + imgRect.h - 26 - i * 24,
              background: '#fff',
              border: `1px solid ${color}`,
              borderLeft: `3px solid ${color}`,
              borderRadius: 4,
              padding: '2px 8px',
              fontSize: 10,
              fontWeight: 600,
              color,
              whiteSpace: 'nowrap',
              pointerEvents: 'none',
              boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
            }}
          >
            ⚠ {f.name}
          </div>
        )
      })}

      {/* Time stamp */}
      {imgRect.w > 0 && (
        <div style={{
          position: 'absolute',
          right: imgRect.left === 0 ? 4 : (imgRect.left === 0 ? 4 : `calc(100% - ${imgRect.left + imgRect.w - 4}px)`),
          top: imgRect.top + 4,
          background: 'rgba(255,255,255,0.9)',
          border: '1px solid #e2e8f0',
          borderRadius: 4,
          padding: '2px 8px',
          fontSize: 11,
          fontFamily: 'monospace',
          color: '#64748b',
          pointerEvents: 'none',
        }}>
          t = {state.time_h.toFixed(2)} h
        </div>
      )}
    </div>
  )
}

const styles = {
  wrapper: {
    position: 'relative',
    width: '100%',
    height: '100%',
    background: '#fff',
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    display: 'block',
  },
  placeholder: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
}
