// frontend-angular/src/app/components/fault-list/fault-list.component.ts
import {
  Component, Input, Output, EventEmitter, OnChanges, ViewChild, ElementRef,
  HostListener, ChangeDetectionStrategy, ChangeDetectorRef,
  ViewEncapsulation,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FaultCatalogue, FaultEntry } from '../../models/simulation.model';

const CAT_COLOR: Record<string, string> = {
  process:   '#ef4444',
  sensor:    '#f97316',
  excursion: '#a855f7',
};
const CAT_LABEL: Record<string, string> = {
  process:   'Process Faults',
  sensor:    'Sensor / Actuator',
  excursion: 'CPP Excursions',
};

@Component({
  selector: 'app-fault-list',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './fault-list.component.html',
  // Styles live here (encapsulation None = global, reliable across any container)
  encapsulation: ViewEncapsulation.None,
  styles: [`
    .fl-container { background:#fff; border:1px solid #e2e8f0; border-radius:10px;
      display:flex; flex-direction:column; height:100%;
      box-shadow:0 1px 3px rgba(0,0,0,.04); }
    .fl-hdr { padding:7px 14px; border-bottom:1px solid #f1f5f9;
      display:flex; align-items:center; gap:10px; flex-shrink:0; }
    .fl-hdr-title { font-size:11px; font-weight:700; color:#374151;
      text-transform:uppercase; letter-spacing:.07em; }
    .fl-off-tag { font-size:10px; color:#9ca3af; background:#f9fafb;
      border:1px solid #e5e7eb; padding:1px 8px; border-radius:99px; }
    .fl-body { display:flex; flex:1; min-height:0; }
    .fl-left { flex:0 0 320px; padding:10px 14px; border-right:1px solid #f1f5f9;
      display:flex; flex-direction:column; gap:8px; }
    /* Trigger */
    .fl-trigger { width:100%; display:flex; align-items:center; justify-content:space-between;
      padding:8px 12px; border:1px solid #d1d5db; border-radius:8px; background:#fff;
      cursor:pointer; font-size:12px; color:#374151; text-align:left;
      transition:border-color .15s,box-shadow .15s; }
    .fl-trigger:hover:not(:disabled) { border-color:#94a3b8; box-shadow:0 0 0 2px #f1f5f9; }
    .fl-trigger:focus { outline:none; border-color:#3b82f6; box-shadow:0 0 0 3px #dbeafe; }
    .fl-trigger:disabled { opacity:.45; cursor:not-allowed; }
    .fl-trigger-label { flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; color:#374151; }
    .fl-arrow { font-size:12px; color:#94a3b8; margin-left:8px; flex-shrink:0;
      transition:transform .15s; display:inline-block; }
    .fl-arrow.open { transform:rotate(180deg); }
    /* Dropdown menu — position:fixed, created via ngStyle, styled here */
    .fl-menu { background:#fff; border:1px solid #e2e8f0; border-radius:10px;
      box-shadow:0 8px 28px rgba(0,0,0,.14), 0 2px 6px rgba(0,0,0,.06);
      overflow-y:auto; max-height:280px; padding:4px 0; }
    .fl-group-hdr { padding:8px 12px 4px; font-size:10px; font-weight:700;
      text-transform:uppercase; letter-spacing:.08em; }
    .fl-opt { display:flex; align-items:center; gap:8px; padding:8px 12px;
      cursor:pointer; font-size:12px; color:#374151; user-select:none; }
    .fl-opt:hover { background:#f8fafc; }
    .fl-opt.selected { background:#eff6ff; color:#1d4ed8; }
    .fl-opt-dot { width:7px; height:7px; border-radius:50%; flex-shrink:0; }
    .fl-opt-name { flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
    /* Trigger btn */
    .fl-trig-btn { background:#dc2626; color:#fff; border:none; border-radius:7px;
      padding:7px 16px; font-size:12px; font-weight:700; cursor:pointer;
      align-self:flex-start; transition:opacity .15s; }
    .fl-trig-btn:disabled { opacity:.38; cursor:not-allowed; }
    /* Description */
    .fl-desc { font-size:11px; color:#64748b; line-height:1.5;
      display:flex; flex-wrap:wrap; align-items:center; gap:5px; padding:2px 0; }
    .fl-dot { width:8px; height:8px; border-radius:50%; flex-shrink:0; display:inline-block; }
    .fl-meta { font-size:10px; color:#94a3b8; font-family:monospace; }
    .fl-err { font-size:11px; color:#b91c1c; background:#fef2f2; padding:4px 8px; border-radius:4px; }
    .fl-ok  { font-size:11px; color:#15803d; background:#dcfce7; padding:4px 8px; border-radius:4px; }
    /* Status */
    .fl-right { flex:1; padding:10px 14px; overflow-y:auto; }
    .fl-status-title { font-size:10px; font-weight:700; color:#94a3b8;
      text-transform:uppercase; letter-spacing:.08em; margin-bottom:6px; }
    .fl-empty { font-size:11px; color:#cbd5e1; font-style:italic; }
    .fl-row { display:flex; align-items:flex-start; gap:8px;
      border-left:3px solid; padding-left:8px; margin-bottom:6px; }
    .fl-sicon { font-size:13px; flex-shrink:0; line-height:1.4; }
    .fl-sname { font-size:12px; font-weight:600; }
    .fl-smeta { font-size:10px; color:#94a3b8; margin-top:1px; }
  `],
})
export class FaultListComponent implements OnChanges {
  @Input()  allFaults:       FaultCatalogue[] = [];
  @Input()  activeFaults:    FaultEntry[]     = [];
  @Input()  recoveredFaults: FaultEntry[]     = [];
  @Input()  simRunning = false;
  // External async state for the trigger action (set by parent after calling the API)
  @Input()  triggerPending = false;
  @Input()  triggerError:  string | null = null;
  @Input()  triggerSuccess: string | null = null;
  /** Emits the fault_id to trigger — parent calls the API and feeds back status via inputs */
  @Output() triggerFaultRequest = new EventEmitter<string>();

  @ViewChild('triggerBtn') triggerRef!: ElementRef<HTMLButtonElement>;

  selectedId = '';
  dropOpen   = false;
  dropStyle: Record<string, string> = {};

  groups: { cat: string; label: string; color: string; items: FaultCatalogue[] }[] = [];

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnChanges(): void {
    const activeIds    = new Set(this.activeFaults.map(f => f.id));
    const recoveredIds = new Set(this.recoveredFaults.map(f => f.id));
    const available    = this.allFaults.filter(f => !activeIds.has(f.id) && !recoveredIds.has(f.id));

    this.groups = ['process', 'sensor', 'excursion']
      .map(cat => ({
        cat, label: CAT_LABEL[cat], color: CAT_COLOR[cat],
        items: available.filter(f => f.category === cat),
      }))
      .filter(g => g.items.length > 0);

    if (this.selectedId && !available.find(f => f.id === this.selectedId)) {
      this.selectedId = '';
    }
  }

  get selectedFault(): FaultCatalogue | undefined {
    return this.allFaults.find(f => f.id === this.selectedId);
  }

  catColor(cat: string): string { return CAT_COLOR[cat] ?? '#64748b'; }

  // ── Dropdown ──────────────────────────────────────────────────────────────

  toggleDrop(event: MouseEvent): void {
    event.stopPropagation();
    if (!this.simRunning) return;

    if (this.dropOpen) {
      this.dropOpen = false;
      this.cdr.markForCheck();
      return;
    }

    const rect   = this.triggerRef.nativeElement.getBoundingClientRect();
    const menuH  = Math.min(this.groups.reduce((n, g) => n + 28 + g.items.length * 36, 0), 280);
    const below  = window.innerHeight - rect.bottom - 8;
    const top    = below >= menuH ? rect.bottom + 4 : rect.top - menuH - 4;

    this.dropStyle = {
      position: 'fixed',
      top:      `${Math.max(8, top)}px`,
      left:     `${rect.left}px`,
      width:    `${Math.max(rect.width, 280)}px`,
      zIndex:   '999999',
    };
    this.dropOpen = true;
    this.cdr.markForCheck();
  }

  // Use mousedown so selection fires BEFORE the document mousedown closes the menu.
  // This guarantees the option is selected even if the host listener fires.
  selectOption(fault: FaultCatalogue, event: MouseEvent): void {
    event.preventDefault();
    event.stopPropagation();
    this.selectedId = fault.id;
    this.dropOpen   = false;
    this.cdr.markForCheck();
  }

  // Close on mousedown outside — fires before click, avoids race with option selection
  @HostListener('document:mousedown', ['$event'])
  onDocMousedown(event: MouseEvent): void {
    if (!this.dropOpen) return;
    const target = event.target as HTMLElement;
    // If the click is inside the trigger or the menu itself, don't close
    if (this.triggerRef?.nativeElement.contains(target)) return;
    if (target.closest('.fl-menu')) return;
    this.dropOpen = false;
    this.cdr.markForCheck();
  }

  @HostListener('document:keydown.escape')
  onEsc(): void {
    if (!this.dropOpen) return;
    this.dropOpen = false;
    this.cdr.markForCheck();
  }

  // ── Trigger fault — emit to parent; parent calls the API ─────────────────

  trigger(): void {
    if (!this.selectedId || this.triggerPending) return;
    this.triggerFaultRequest.emit(this.selectedId);
    this.selectedId = '';
    this.cdr.markForCheck();
  }
}

<div class="fl-container">

  <!-- Header -->
  <div class="fl-hdr">
    <span class="fl-hdr-title">⚠ Fault Injection</span>
    <span class="fl-off-tag" *ngIf="!simRunning">simulation not running</span>
  </div>

  <div class="fl-body">

    <!-- Left: selector + trigger -->
    <div class="fl-left">

      <!-- Trigger button -->
      <button
        #triggerBtn
        class="fl-trigger"
        [disabled]="!simRunning"
        (click)="toggleDrop($event)"
      >
        <span class="fl-trigger-label">
          {{ selectedFault?.name || '— Select a fault to inject —' }}
        </span>
        <span class="fl-arrow" [class.open]="dropOpen">▾</span>
      </button>

      <!-- Dropdown menu: rendered fixed so it escapes all overflow:hidden ancestors -->
      <div
        *ngIf="dropOpen"
        class="fl-menu"
        [style.position]="'fixed'"
        [style.top]="dropStyle['top']"
        [style.left]="dropStyle['left']"
        [style.width]="dropStyle['width']"
        [style.z-index]="dropStyle['zIndex']"
      >
        <ng-container *ngFor="let g of groups">
          <div class="fl-group-hdr" [style.color]="g.color">◆ {{ g.label }}</div>
          <div
            *ngFor="let f of g.items"
            class="fl-opt"
            [class.selected]="selectedId === f.id"
            (mousedown)="selectOption(f, $event)"
          >
            <span class="fl-opt-dot" [style.background]="g.color"></span>
            <span class="fl-opt-name">{{ f.name }}</span>
          </div>
        </ng-container>
      </div>

      <!-- Trigger button -->
      <button
        class="fl-trig-btn"
        (click)="trigger()"
        [disabled]="!simRunning || !selectedId || triggerPending"
      >
        {{ triggerPending ? 'Triggering…' : '▶  Trigger Fault' }}
      </button>

      <!-- Selected fault description -->
      <div class="fl-desc" *ngIf="selectedFault">
        <span class="fl-dot" [style.background]="catColor(selectedFault.category)"></span>
        <span>{{ selectedFault.desc }}</span>
        <span class="fl-meta">Default: t = {{ selectedFault.trigger_default_h }} h</span>
      </div>

      <div class="fl-err" *ngIf="triggerError">⚠ {{ triggerError }}</div>
      <div class="fl-ok"  *ngIf="triggerSuccess">✓ {{ triggerSuccess }} triggered</div>
    </div>

    <!-- Right: fault status -->
    <div class="fl-right">
      <div class="fl-status-title">Fault Status</div>

      <div class="fl-empty" *ngIf="!activeFaults.length && !recoveredFaults.length">
        No faults triggered yet
      </div>

      <div *ngFor="let f of activeFaults" class="fl-row"
           [style.border-left-color]="catColor(f.category)">
        <span class="fl-sicon" [style.color]="catColor(f.category)">⚠</span>
        <div>
          <div class="fl-sname" [style.color]="catColor(f.category)">{{ f.name }}</div>
          <div class="fl-smeta">Active · t = {{ f.triggered_at_h.toFixed(1) }} h</div>
        </div>
      </div>

      <div *ngFor="let f of recoveredFaults" class="fl-row" style="border-left-color:#22c55e">
        <span class="fl-sicon" style="color:#22c55e">✓</span>
        <div>
          <div class="fl-sname" style="color:#15803d">{{ f.name }}</div>
          <div class="fl-smeta">Recovered</div>
        </div>
      </div>
    </div>

  </div>
</div>

// frontend/src/components/FaultList.jsx
import { useState } from 'react'
import { triggerFault } from '../services/api.js'

const CAT_COLOR = { process: '#ef4444', sensor: '#f97316', excursion: '#a855f7' }
const CAT_LABEL = { process: 'Process Faults', sensor: 'Sensor / Actuator', excursion: 'CPP Excursions' }

export default function FaultList({ allFaults, activeFaults, recoveredFaults, simRunning }) {
  const [selectedId, setSelectedId] = useState('')
  const [triggering,  setTriggering]  = useState(false)
  const [error,       setError]       = useState(null)
  const [lastOk,      setLastOk]      = useState(null)

  const activeIds    = new Set((activeFaults    || []).map(f => f.id))
  const recoveredIds = new Set((recoveredFaults || []).map(f => f.id))

  // Faults still available to trigger (not yet active or recovered)
  const available = (allFaults || []).filter(f => !activeIds.has(f.id) && !recoveredIds.has(f.id))
  const selectedFault = available.find(f => f.id === selectedId) ?? null

  async function handleTrigger() {
    if (!selectedId) return
    setError(null)
    setLastOk(null)
    setTriggering(true)
    try {
      await triggerFault(selectedId)
      setLastOk(selectedFault?.name ?? selectedId)
      setSelectedId('')
    } catch (e) {
      setError(e.message)
    } finally {
      setTriggering(false)
    }
  }

  const groups = ['process', 'sensor', 'excursion'].map(cat => ({
    cat,
    items: available.filter(f => f.category === cat),
  })).filter(g => g.items.length > 0)

  return (
    <div style={s.container}>
      {/* Header */}
      <div style={s.header}>
        <span style={s.headerTitle}>⚠ Fault Injection</span>
        {!simRunning && <span style={s.offTag}>simulation not running</span>}
      </div>

      <div style={s.body}>
        {/* Left: selector + trigger */}
        <div style={s.left}>
          <div style={s.selectWrap}>
            <select
              value={selectedId}
              onChange={e => setSelectedId(e.target.value)}
              disabled={!simRunning}
              style={{ ...s.select, opacity: simRunning ? 1 : 0.5 }}
            >
              <option value="">— Select a fault —</option>
              {groups.map(({ cat, items }) => (
                <optgroup key={cat} label={`◆ ${CAT_LABEL[cat]}`}>
                  {items.map(f => (
                    <option key={f.id} value={f.id}>{f.name}</option>
                  ))}
                </optgroup>
              ))}
            </select>
          </div>

          <button
            onClick={handleTrigger}
            disabled={!simRunning || !selectedId || triggering}
            style={{
              ...s.triggerBtn,
              opacity: (!simRunning || !selectedId || triggering) ? 0.4 : 1,
              cursor: (!simRunning || !selectedId) ? 'not-allowed' : 'pointer',
            }}
          >
            {triggering ? 'Triggering…' : '▶  Trigger Fault'}
          </button>

          {/* Fault description */}
          {selectedFault && (
            <div style={s.desc}>
              <span style={{ ...s.catDot, background: CAT_COLOR[selectedFault.category] }} />
              <span style={{ color: '#475569' }}>{selectedFault.desc}</span>
              <span style={s.defaultTime}> Default: t = {selectedFault.trigger_default_h} h</span>
            </div>
          )}

          {error   && <div style={s.errMsg}>⚠ {error}</div>}
          {lastOk  && <div style={s.okMsg}>✓ {lastOk} triggered</div>}
        </div>

        {/* Right: active + recovered status */}
        <div style={s.right}>
          <div style={s.statusTitle}>Fault Status</div>

          {(activeFaults || []).length === 0 && (recoveredFaults || []).length === 0 && (
            <div style={s.emptyStatus}>No faults triggered yet</div>
          )}

          {(activeFaults || []).map(f => (
            <div key={f.id} style={{ ...s.statusRow, borderLeftColor: CAT_COLOR[f.category] || '#ef4444' }}>
              <span style={{ ...s.statusIcon, color: CAT_COLOR[f.category] }}>⚠</span>
              <div style={s.statusInfo}>
                <div style={{ ...s.statusName, color: CAT_COLOR[f.category] }}>{f.name}</div>
                <div style={s.statusMeta}>Active · triggered t = {f.triggered_at_h?.toFixed(1)} h</div>
              </div>
            </div>
          ))}

          {(recoveredFaults || []).map(f => (
            <div key={f.id} style={{ ...s.statusRow, borderLeftColor: '#22c55e' }}>
              <span style={{ ...s.statusIcon, color: '#22c55e' }}>✓</span>
              <div style={s.statusInfo}>
                <div style={{ ...s.statusName, color: '#15803d' }}>{f.name}</div>
                <div style={s.statusMeta}>Recovered</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

const s = {
  container: {
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  header: {
    padding: '7px 14px',
    borderBottom: '1px solid #f1f5f9',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: 11, fontWeight: 700, color: '#374151',
    textTransform: 'uppercase', letterSpacing: '0.07em',
  },
  offTag: {
    fontSize: 10, color: '#9ca3af', background: '#f9fafb',
    border: '1px solid #e5e7eb', padding: '1px 8px', borderRadius: 99,
  },
  body: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  left: {
    flex: '0 0 340px',
    padding: '10px 14px',
    borderRight: '1px solid #f1f5f9',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  selectWrap: { display: 'flex', flexDirection: 'column' },
  select: {
    width: '100%',
    padding: '7px 10px',
    border: '1px solid #d1d5db',
    borderRadius: 7,
    fontSize: 12,
    color: '#1e293b',
    background: '#fff',
    cursor: 'pointer',
    outline: 'none',
  },
  triggerBtn: {
    background: '#dc2626',
    color: '#fff',
    border: 'none',
    borderRadius: 7,
    padding: '7px 16px',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.02em',
    transition: 'opacity 0.15s',
    alignSelf: 'flex-start',
  },
  desc: {
    fontSize: 11,
    color: '#64748b',
    lineHeight: 1.5,
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 5,
    padding: '4px 0',
  },
  catDot: { width: 8, height: 8, borderRadius: '50%', flexShrink: 0, display: 'inline-block' },
  defaultTime: { fontSize: 10, color: '#94a3b8', fontFamily: 'monospace' },
  errMsg: { fontSize: 11, color: '#b91c1c', background: '#fef2f2', padding: '4px 8px', borderRadius: 4 },
  okMsg:  { fontSize: 11, color: '#15803d', background: '#dcfce7', padding: '4px 8px', borderRadius: 4 },
  right: {
    flex: 1,
    padding: '10px 14px',
    overflowY: 'auto',
  },
  statusTitle: {
    fontSize: 10, fontWeight: 700, color: '#94a3b8',
    textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6,
  },
  emptyStatus: { fontSize: 11, color: '#cbd5e1', fontStyle: 'italic' },
  statusRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    borderLeft: '3px solid',
    paddingLeft: 8,
    marginBottom: 6,
  },
  statusIcon: { fontSize: 13, flexShrink: 0, lineHeight: 1.4 },
  statusInfo: {},
  statusName: { fontSize: 12, fontWeight: 600 },
  statusMeta: { fontSize: 10, color: '#94a3b8', marginTop: 1 },
}
