// frontend/src/components/RecoveryBar.jsx
import { useState } from 'react'
import { applyRecovery, declineRecovery } from '../services/api.js'

export default function RecoveryBar({ prompt }) {
  const [busy, setBusy] = useState(null)   // 'apply' | 'decline' | null

  if (!prompt) {
    return (
      <div style={{ ...s.bar, background: '#f8fafc', borderColor: '#e2e8f0' }}>
        <span style={s.idle}>No active recovery prompts</span>
      </div>
    )
  }

  async function handleApply() {
    setBusy('apply')
    try { await applyRecovery(prompt.fault_id) } finally { setBusy(null) }
  }
  async function handleDecline() {
    setBusy('decline')
    try { await declineRecovery(prompt.fault_id) } finally { setBusy(null) }
  }

  const urgent = prompt.remaining_h < 0.5
  const accentColor = urgent ? '#ef4444' : '#f59e0b'

  return (
    <div style={{ ...s.bar, background: urgent ? '#fef2f2' : '#fffbeb', borderColor: accentColor }}>
      <span style={{ fontSize: 16, flexShrink: 0 }}>⚠</span>

      <div style={s.info}>
        <span style={{ color: accentColor, fontWeight: 700 }}>{prompt.fault_name}</span>
        <span style={s.sep}> › </span>
        <span style={{ color: '#374151' }}>{prompt.recovery_name}</span>
        <span style={s.sep}> │ </span>
        <span style={{ color: accentColor, fontFamily: 'monospace', fontSize: 12 }}>
          auto-decline in {prompt.remaining_h.toFixed(1)} h
        </span>
        <span style={{ color: '#9ca3af', fontFamily: 'monospace', fontSize: 11 }}>
          {' '}(deadline t={prompt.deadline_h.toFixed(1)} h)
        </span>
      </div>

      <div style={s.btns}>
        <button
          onClick={handleApply}
          disabled={busy !== null}
          style={{ ...s.btn, background: '#dcfce7', color: '#15803d', border: '1px solid #86efac', opacity: busy ? 0.5 : 1 }}
        >
          {busy === 'apply' ? '…' : '✓  Apply Recovery'}
        </button>
        <button
          onClick={handleDecline}
          disabled={busy !== null}
          style={{ ...s.btn, background: '#fee2e2', color: '#b91c1c', border: '1px solid #fca5a5', opacity: busy ? 0.5 : 1 }}
        >
          {busy === 'decline' ? '…' : '✗  Decline'}
        </button>
      </div>
    </div>
  )
}

const s = {
  bar: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '7px 14px',
    border: '1px solid',
    borderRadius: 8,
    minHeight: 44,
    transition: 'border-color 0.3s, background 0.3s',
  },
  idle: { fontSize: 12, color: '#94a3b8', fontFamily: 'monospace' },
  info: { flex: 1, fontSize: 13, display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 2 },
  sep: { color: '#cbd5e1' },
  btns: { display: 'flex', gap: 8, flexShrink: 0 },
  btn: {
    border: 'none',
    borderRadius: 6,
    padding: '5px 14px',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'opacity 0.15s',
  },
}

// frontend-angular/src/app/components/recovery-bar/recovery-bar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RecoveryPrompt } from '../../models/simulation.model';

@Component({
  selector: 'app-recovery-bar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './recovery-bar.component.html',
})
export class RecoveryBarComponent {
  @Input()  prompt:  RecoveryPrompt | null = null;
  @Input()  busy:    'apply' | 'decline' | null = null;
  /** Emits fault_id — parent calls applyRecovery(faultId) */
  @Output() applyRequest   = new EventEmitter<string>();
  /** Emits fault_id — parent calls declineRecovery(faultId) */
  @Output() declineRequest = new EventEmitter<string>();

  get urgent(): boolean { return (this.prompt?.remaining_h ?? 99) < 0.5; }
  get accentColor(): string { return this.urgent ? '#ef4444' : '#f59e0b'; }

  apply():   void { if (this.prompt) this.applyRequest.emit(this.prompt.fault_id); }
  decline(): void { if (this.prompt) this.declineRequest.emit(this.prompt.fault_id); }
}

<div class="bar idle" *ngIf="!prompt">
  <span class="idle-txt">No active recovery prompts</span>
</div>

<div class="bar active" *ngIf="prompt"
     [style.background]="urgent ? '#fef2f2' : '#fffbeb'"
     [style.border-color]="accentColor">
  <span class="icon">⚠</span>
  <div class="info">
    <span [style.color]="accentColor" class="fw">{{ prompt.fault_name }}</span>
    <span class="sep"> › </span>
    <span>{{ prompt.recovery_name }}</span>
    <span class="sep"> │ </span>
    <span [style.color]="accentColor" class="mono">auto-decline in {{ prompt.remaining_h.toFixed(1) }} h</span>
    <span class="muted mono"> (deadline t={{ prompt.deadline_h.toFixed(1) }} h)</span>
  </div>
  <div class="btns">
    <button class="btn-yes" (click)="apply()"   [disabled]="busy !== null">{{ busy==='apply'   ? '…' : '✓  Apply Recovery' }}</button>
    <button class="btn-no"  (click)="decline()" [disabled]="busy !== null">{{ busy==='decline' ? '…' : '✗  Decline' }}</button>
  </div>
</div>

<style>
.bar { display:flex; align-items:center; gap:10px; padding:7px 14px; border:1px solid; border-radius:8px; min-height:44px; transition:border-color .3s,background .3s; }
.idle { background:#f8fafc; border-color:#e2e8f0; }
.idle-txt { font-size:12px; color:#94a3b8; font-family:monospace; }
.icon { font-size:16px; flex-shrink:0; }
.info { flex:1; font-size:13px; display:flex; flex-wrap:wrap; align-items:center; gap:2px; }
.sep { color:#cbd5e1; }
.fw { font-weight:700; }
.mono { font-family:monospace; font-size:12px; }
.muted { color:#9ca3af; font-size:11px; }
.btns { display:flex; gap:8px; flex-shrink:0; }
.btn-yes, .btn-no { border:none; border-radius:6px; padding:5px 14px; font-size:12px; font-weight:600; cursor:pointer; }
.btn-yes { background:#dcfce7; color:#15803d; }
.btn-no  { background:#fee2e2; color:#b91c1c; }
.btn-yes:disabled, .btn-no:disabled { opacity:.5; cursor:not-allowed; }
</style>
